name: Deploy production

on:
  # This job runs when a new release is published using https://github.com/theodo/hubspot-ace-integration/releases/new
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/fermium"
          cache: "npm"
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::772972000351:role/github-actions
          aws-region: eu-west-1
      - run: npm i
      - run: npm run type
      - run: npm run test
      - run: npx sls deploy --stage prod
